Replace deprecated Mobius (C#) with .NET
awesome-spark/awesome-spark pull request #182
Opened 2020-06-19 05:10 UTC by manojmallela

Updates `Packages/Language Bindings` with .NET API.

2020-06-23 07:10 UTC, eliasah commented
Hello @manojmallela I'd rather we keep Mobius for now even though it's deprecated. You can also add the .Net connector

2020-09-21 06:11 UTC, zero323 requested changes
Could you please make changes, as request here https://github.com/awesome-spark/awesome-spark/pull/182#issuecomment-647954498? Thanks!

2020-09-22 04:23 UTC, manojmallela commented
Hi @zero323, refactored as per the comment, please review.

2020-09-22 19:01 UTC, zero323 approved these changes
The comment notwithstanding, LGTM

2020-09-22 19:01 UTC, zero323 commented on README.md
>  * [Mobius](https://github.com/Microsoft/Mobius) <img src="https://img.shields.io/github/last-commit/Microsoft/Mobius.svg"> - C# bindings.
We could add something around these lines:

> (Deprecated in favor of .NET for Apache Spark)

2020-10-01 20:01 UTC, merged